### ISSUE TITLE
QUIC network implementation

### ISSUE THREAD

**Issue by nikkolasg** [ConsenSys/handel#4]
Add a QUIC network implementation to Handel.

**Comment by bkolad** [comment]
The QUIC network is around 4 times slower than the UDP network. 
The performance hit comes from the handshake phase and QUIC-go doesn't support 0-RTT handshake yet:
https://github.com/lucas-clemente/quic-go/issues/438

After playing with the AcceptCookie callback I managed to decrease the performance hit to 3.5x of UDP network for 500 nodes.
